---

hermes_base_url: http://130.238.178.239:9000/api/0.1
hermes_user: dummy_user
hermes_token: my_token

summary_host: testuppmax
summary_user: arteria
summary_host_key: /path/to/ssh/key
summary_destination: /tmp/summaries/

remote_host: testuppmax
remote_user: arteria
remote_host_key: /path/to/ssh/key
remote_destination: /tmp/runfolders/
remote_sisyphus_location: /opt/arteria/arteria-siswrap-env/deps/sisyphus/sisyphus-latest

ngi_pipeline_url: https://irma1.uppmax.uu.se:4444/ngi_pipeline_upps

irma_api_key: aaaaaaaaaaaaaaaaaaaaaaaaaaaaa
irma_remote_path: ./staging/
irma_checksum_base_url: https://irma1.uppmax.uu.se:4444/arteria_checksum_staging/api/1.0
irma_siswrap_base_url: https://irma1.uppmax.uu.se:4444/arteria_siswrap_staging/api/1.0

irma_replace_expressions:
 - 's/UPPNEX_PROJECT: a2009002/UPPNEX_PROJECT: ngi2016001/'
 - 's/UPPNEX_QOS: seqver/#UPPNEX_QOS: seqver/'

send_mail_to: example.mail.address@send.errors.to

runfolder_service_port: 10800
bcl2fastq_service_port: 10900
siswrap_service_port: 10700

# The service URL polled in the runfolder sensor:
runfolder_svc_urls:
  - http://testarteria1:10800

charon_api_token: dummy_token
charon_base_url: http://charon.url
slack_webhook_url: https://slack.webhook.url
charon_status_report_slack_channel: "#bottest"

